loki:
  auth_enabled: false

singleBinary:
  replicas: 1

ingester:
  replicas: 1

querier:
  replicas: 1

queryFrontend:
  replicas: 1

gateway:
  enabled: false

service:
  type: ClusterIP

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

storage:
  type: filesystem